# Generated by Django 4.2.4 on 2023-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="fifthtime",
            field=models.TextField(default="02:00-03:00"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="firsttime",
            field=models.TextField(default="09:00-10:00"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="fourthtime",
            field=models.TextField(default="01:00-02:00"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="secondtime",
            field=models.TextField(default="10:00-11:00"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="sixthtime",
            field=models.TextField(default="03:00-04:00"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="thirdtime",
            field=models.TextField(default="11:00-12:00"),
        ),
    ]
