# Generated by Django 4.2.4 on 2023-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_alter_timetable_fifthtime_alter_timetable_firsttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fifthtime',
            field=models.TextField(default='02:00 PM-03:00 PM'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='firsttime',
            field=models.TextField(default='09:00 AM-10:00 AM'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourthtime',
            field=models.TextField(default='01:00 PM-02:00 PM'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='secondtime',
            field=models.TextField(default='10:00 AM-11:00 AM'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixthtime',
            field=models.TextField(default='03:00 PM-04:00 PM'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thirdtime',
            field=models.TextField(default='11:00 AM-12:00 PM'),
        ),
    ]
