# Generated by Django 4.1.13 on 2023-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_ieee_membership_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ieee_membership_no',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
