# Generated by Django 4.1.13 on 2023-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_update_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscore',
            name='team_score_json',
        ),
        migrations.AddField(
            model_name='teamscore',
            name='score',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='team',
            field=models.TextField(default=''),
        ),
    ]
