# Generated by Django 4.1.13 on 2023-11-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_update_board', '0005_teamitemaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamitems',
            name='status',
            field=models.TextField(default='Done'),
        ),
    ]
