# Generated by Django 4.1.13 on 2023-11-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_update_board', '0008_teamitems_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamitems',
            name='item_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
