# Generated by Django 4.2.4 on 2023-09-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0002_forumevents_hashtags_registration_gender_likeevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeevent',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RemoveField(
            model_name='likeevent',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='forumevents',
            name='status',
            field=models.CharField(default='Upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forum_events.forumevents'),
        ),
    ]
