# Generated by Django 4.2.4 on 2023-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0004_remove_likeevent_user_id_likeevent_user_and_more'),
        ('forum_events', '0006_alter_forumevents_poster_image_url_and_more'),
    ]

    operations = [
    ]
