# Generated by Django 4.2.4 on 2023-09-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_alter_user_managers_and_more'),
        ('forum_events', '0007_merge_20230911_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
