# Generated by Django 4.2.4 on 2023-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_events", "0009_alter_likeevent_event_id_alter_registration_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumevents",
            name="no_of_views",
            field=models.IntegerField(default=0),
        ),
    ]
