# Generated by Django 4.1.13 on 2023-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0012_remove_forumevents_poster_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevents',
            name='poster_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumevents',
            name='thumbnail_poster_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
