# Generated by Django 4.1.13 on 2023-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0016_alter_forumevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevents',
            name='event_date',
            field=models.CharField(default='', max_length=15),
        ),
    ]
