# Generated by Django 4.1.13 on 2024-02-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0018_alter_forumevents_whatsapp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeevent',
            name='date',
        ),
    ]
