# Generated by Django 4.1.13 on 2024-02-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0019_remove_likeevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeevent',
            name='user_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
