# Generated by Django 4.1.13 on 2024-02-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0020_alter_likeevent_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone_no',
        ),
    ]
