# Generated by Django 4.1.13 on 2024-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0021_remove_registration_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
