# Generated by Django 4.1.13 on 2024-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0022_registration_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevents',
            name='poster_image',
            field=models.ImageField(upload_to='forum/events/images/'),
        ),
    ]
