# Generated by Django 4.2.4 on 2023-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_cec', '0004_alter_filestore_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostore',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
