# Generated by Django 4.1.13 on 2023-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_cec', '0005_videostore_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='video_url',
            field=models.TextField(blank=True, default=None),
        ),
    ]
