# Generated by Django 4.1.13 on 2023-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_cec', '0008_alter_filestore_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestore',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
