# Generated by Django 4.2.4 on 2023-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_admission_no_user_branch_user_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
