# Generated by Django 4.2.4 on 2023-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
