# Generated by Django 4.1.13 on 2023-12-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ieee_membership_no',
            field=models.CharField(blank=True, default='null', max_length=10, null=True),
        ),
    ]
