# Generated by Django 4.1.13 on 2024-02-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_ieee_membership_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
    ]
