# Generated by Django 4.2.4 on 2023-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=100)),
                ('forum_description', models.TextField(default='No description')),
                ('email_id', models.TextField()),
                ('forum_role_name', models.CharField(max_length=100)),
                ('forum_image', models.ImageField(upload_to='forum/management/images/')),
                ('thumbnail_forum_image', models.ImageField(blank=True, null=True, upload_to='forum/management/thumbnails/')),
                ('logged_in', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
