# Generated by Django 4.2.4 on 2023-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='gallery/cec/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/cec/thumbnails/')),
                ('media_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
