# Generated by Django 4.2.4 on 2023-08-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_cec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='tag',
            field=models.CharField(default='image', max_length=150),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='media_file',
            field=models.FileField(upload_to='gallery/cec/images/'),
        ),
        migrations.CreateModel(
            name='VideoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='gallery/cec/videos/')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_cec.filestore')),
            ],
        ),
    ]
