# Generated by Django 4.2.4 on 2023-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_cec', '0002_filestore_tag_alter_filestore_media_file_videostore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestore',
            name='tag',
            field=models.CharField(default='img', max_length=150),
        ),
    ]
