# Generated by Django 4.2.4 on 2023-09-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_management', '0003_addforum_display_name'),
        ('forum_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='forum/stories/media/')),
                ('thumbnail_media_file', models.FileField(blank=True, null=True, upload_to='forum/stories/thumbnails/')),
                ('media_url', models.TextField(blank=True, null=True)),
                ('thumbnail_media_url', models.TextField(blank=True, null=True)),
                ('forum_tag', models.TextField(default='')),
                ('file_tag', models.TextField(default='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_management.addforum')),
            ],
        ),
    ]
