# Generated by Django 4.2.4 on 2023-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_stories', '0002_forumstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumstories',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
