# Generated by Django 4.2.4 on 2023-09-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, upload_to='forum/events/posters/')),
                ('poster_image_url', models.TextField(blank=True, null=True)),
                ('thumbnail_poster_image', models.ImageField(blank=True, null=True, upload_to='forum/events/thumbnails/')),
                ('thumbnail_poster_image_url', models.TextField(blank=True, null=True)),
                ('whatsapp_link', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(blank=True, max_length=100)),
                ('hashtags', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_announcements.forumannouncements')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
    ]
