# Generated by Django 4.2.4 on 2023-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_announcements", "0003_forumannouncements_no_of_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumannouncements",
            name="no_of_views",
        ),
        migrations.AddField(
            model_name="likeannouncement",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="likeannouncement",
            name="views",
            field=models.BooleanField(default=True),
        ),
    ]
