# Generated by Django 4.1.13 on 2023-11-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_update_board', '0006_teamitems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamitems',
            name='status',
        ),
        migrations.AddField(
            model_name='teamitems',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
