# Generated by Django 4.2.4 on 2023-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights_cec', '0003_highlightimage_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightimage',
            name='tag',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
