# Generated by Django 4.2.4 on 2023-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_images/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='homepage_images/thumbnails/')),
            ],
        ),
    ]
