# Generated by Django 4.2.4 on 2023-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
