# Generated by Django 4.2.4 on 2023-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_images', '0002_image_image_url_image_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
    ]
