# Generated by Django 4.2.4 on 2023-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumannouncements',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to='forum/announcements/posters/'),
        ),
        migrations.AlterField(
            model_name='forumannouncements',
            name='thumbnail_poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/announcements/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='likeannouncement',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
