# Generated by Django 4.2.4 on 2023-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_announcements", "0002_alter_forumannouncements_poster_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumannouncements",
            name="no_of_views",
            field=models.IntegerField(default=0),
        ),
    ]
