# Generated by Django 4.2.4 on 2023-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_gender'),
        ('forum_announcements', '0004_remove_forumannouncements_no_of_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumannouncements',
            name='button_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumannouncements',
            name='button_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likeannouncement',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='likeannouncement',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
