# Generated by Django 4.1.13 on 2024-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_announcements', '0005_forumannouncements_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeannouncement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='likeannouncement',
            name='user',
        ),
        migrations.AddField(
            model_name='likeannouncement',
            name='user_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
