# Generated by Django 4.1.13 on 2024-03-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_announcements', '0006_remove_likeannouncement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumannouncements',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to='forum/announcements/images/'),
        ),
    ]
