# Generated by Django 4.2.4 on 2023-08-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='highlights_images/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='highlights_images/thumbnails/')),
                ('image_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
            ],
        ),
    ]
