# Generated by Django 4.1.13 on 2024-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_alter_timetable_fifthtime_alter_timetable_firsttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fifthcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='firstcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourthcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='secondcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixthcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thirdcode',
            field=models.TextField(null=True),
        ),
    ]
