# Generated by Django 4.2.4 on 2023-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forumEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(upload_to='forum/events/posters/')),
                ('thumbnail_poster_image', models.ImageField(blank=True, null=True, upload_to='forum/events/thumbnails/')),
                ('register_button_link', models.TextField(blank=True, default='vcec_form', null=True)),
                ('whatsapp_link', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('semester', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('email', models.TextField()),
                ('phone_no', models.TextField()),
            ],
        ),
    ]
