# Generated by Django 4.2.4 on 2023-09-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevents',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.TextField(default='Other'),
        ),
        migrations.CreateModel(
            name='LikeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_events.forumevents')),
            ],
        ),
    ]
