# Generated by Django 4.2.4 on 2023-09-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_alter_user_managers_and_more"),
        ("forum_events", "0003_rename_event_likeevent_event_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likeevent",
            name="user_id",
        ),
        migrations.AddField(
            model_name="likeevent",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="forum_events.forumevents",
            ),
        ),
    ]
