# Generated by Django 4.2.4 on 2023-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0004_alter_forumevents_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevents',
            name='poster_image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forumevents',
            name='thumbnail_poster_image_url',
            field=models.TextField(blank=True),
        ),
    ]
