# Generated by Django 4.2.4 on 2023-09-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_alter_user_managers_and_more'),
        ('forum_events', '0006_alter_forumevents_poster_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='likeevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
