# Generated by Django 4.2.4 on 2023-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0008_alter_likeevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeevent',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
