# Generated by Django 4.2.4 on 2023-09-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0011_remove_forumevents_no_of_views_likeevent_is_liked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumevents',
            name='poster_image_url',
        ),
        migrations.RemoveField(
            model_name='forumevents',
            name='thumbnail_poster_image_url',
        ),
        migrations.RemoveField(
            model_name='likeevent',
            name='user',
        ),
        migrations.AddField(
            model_name='likeevent',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='forumevents',
            name='poster_image',
            field=models.ImageField(upload_to='forum/events/posters/'),
        ),
        migrations.AlterField(
            model_name='forumevents',
            name='published_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forumevents',
            name='status',
            field=models.CharField(default='Upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='forumevents',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='likeevent',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_events.forumevents'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_events.forumevents'),
        ),
    ]
