# Generated by Django 4.1.13 on 2023-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_events', '0017_alter_forumevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevents',
            name='whatsapp_link',
            field=models.TextField(default=''),
        ),
    ]
