# Generated by Django 4.2.4 on 2023-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_management', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='addforum',
            name='display_name',
            field=models.CharField(default='No display name', max_length=100),
        ),
    ]
