"""
Django settings for vcec_bk project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = bool(os.environ.get("DEBUG", default=0))

allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")

# Split the environment variable if it is not an empty string
# ALLOWED_HOSTS = allowed_hosts_env.split() if allowed_hosts_env else []

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'channels',
    'channels_postgres',
    # 'daphne',
    'storages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'cecify',
    'notices',
    'homepage_images',
    'staff_info',
    'highlights_cec',
    'gallery_cec',
    'forum_events',
    'forum_announcements',
    'timetables',
    'forum_management',
    'forum_stories',
    'fixtures_ashwa',

]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:4200",
    "https://localhost:3000",
    "http://localhost:5173",
    "https://localhost:5173",
    "https://localhost:4200",
]


CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_ALL_HEADERS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'channels.middleware.WebSocketMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vcec_bk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vcec_bk.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    },

    'channels_postgres': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 1,
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_postgres.core.PostgresChannelLayer',
        'CONFIG': {
            "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
            "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
            "USER": os.environ.get("SQL_USER", "user"),
            "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
            "HOST": os.environ.get("SQL_HOST", "localhost"),
            "PORT": os.environ.get("SQL_PORT", "5432"),
        },
    },
}


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # Replace with your Redis server address and database number
        'LOCATION': f'rediss://{os.environ.get("REDIS_LOCATION")}:{os.environ.get("REDIS_PORT")}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': os.environ.get("REDIS_PASSWORD"),
            'SSL': True,

        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# ASGI_APPLICATION = "vcec_bk.routing.application"

# Celery settings
CELERY_BROKER_URL = f'rediss://:{os.environ.get("REDIS_PASSWORD")}@{os.environ.get("REDIS_LOCATION")}:{os.environ.get("REDIS_PORT")}' + \
    '?ssl_cert_reqs=none'
CELERY_RESULT_BACKEND = f'rediss://:{os.environ.get("REDIS_PASSWORD")}@{os.environ.get("REDIS_LOCATION")}:{os.environ.get("REDIS_PORT")}' + \
    '?ssl_cert_reqs=none'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE_FILENAME = 'celerybeat-schedule'


CELERY_BEAT_SCHEDULE = {
    # 'ktu-notices-every-15-minutes': {
    #     'task': 'notices.tasks.ktu_webs_announce_task',
    #     'schedule': 900,  # 15 minutes in seconds
    # },
    'forum-stories-every-1-minutes': {
        'task': 'forum_stories.tasks.checkIfStoriesExpired',
        'schedule': 60,
    },
    'student-time-table-cronjob-1': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=8, minute=30),
    },
    'student-time-table-cronjob-2': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=9),
    },
    'student-time-table-cronjob-3': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=9, minute=50),
    },
    'student-time-table-cronjob-4': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=10),
    },
    'student-time-table-cronjob-5': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=10, minute=40),
    },
    'student-time-table-cronjob-6': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=10, minute=50),
    },
    'student-time-table-cronjob-7': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=11),
    },
    'student-time-table-cronjob-8': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=11, minute=40),
    },
    'student-time-table-cronjob-9': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=12),
    },
    'student-time-table-cronjob-10': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=12, minute=30),
    },
    'student-time-table-cronjob-11': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=13),
    },
    'student-time-table-cronjob-12': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=14),
    },
    'student-time-table-cronjob-13': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=15),
    },
    'student-time-table-cronjob-14': {
        'task': 'timetables.tasks.AutoTimeTableSystem',
        'schedule': crontab(hour=16),
    },
    # 'Score-Board': {
    #     'task': 'live_update_board.tasks.RealTimeTask',
    #     'schedule': 40 # this means, the task will run itself every second
    # },
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")


ACCESS_TOKEN_EXPIRATION = 120  # Adjust as needed
REFRESH_TOKEN_EXPIRATION = 483840  # Adjust as needed


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


DEFAULT_FILE_STORAGE = 'vcec_bk.azure_storages.AzureMediaStorage'
STATICFILES_STORAGE = 'vcec_bk.azure_storages.AzureStaticStorage'

STATIC_LOCATION = "static"
MEDIA_LOCATION = "media"

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'mediafiles'

AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_ACCOUNT_NAME = os.environ.get("AZURE_STORAGE_ACCOUNT_NAME")
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
