# Generated by Django 4.1.13 on 2024-03-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioSeasonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(unique=True)),
                ('color1', models.CharField(max_length=6)),
                ('color2', models.CharField(max_length=6)),
                ('color3', models.CharField(max_length=6)),
                ('color4', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RadioEpisodesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='radio/episodes/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='radio/episodes/thumbnails/')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cecify.radioseasondetails')),
            ],
        ),
    ]
