# Generated by Django 4.1.13 on 2024-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioepisodesdetails',
            name='image',
            field=models.ImageField(upload_to='cecify/radio/episodes/images/'),
        ),
        migrations.AlterField(
            model_name='radioepisodesdetails',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cecify/radio/episodes/thumbnails/'),
        ),
    ]
