# Generated by Django 4.1.13 on 2024-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecify', '0002_alter_radioepisodesdetails_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioepisodesdetails',
            name='google_podcast_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='radioepisodesdetails',
            name='spotify_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='radioepisodesdetails',
            name='youtube_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
