# Generated by Django 4.1.13 on 2024-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecify', '0003_radioepisodesdetails_google_podcast_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioepisodesdetails',
            name='season_number',
            field=models.IntegerField(default=0),
        ),
    ]
