# Generated by Django 4.1.13 on 2024-03-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecify', '0005_alter_radioepisodesdetails_episode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='radioepisodesdetails',
            unique_together={('episode', 'season_number')},
        ),
    ]
