name: Remove old artifacts

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '3 month'

