# Generated by Django 4.2.4 on 2023-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('designation', models.TextField()),
                ('email_id', models.TextField()),
                ('mobile_no', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
