# Generated by Django 4.1.13 on 2024-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
