# Generated by Django 4.1.13 on 2024-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_info', '0003_alter_staffinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='mobile_no',
            field=models.TextField(unique=True),
        ),
    ]
